[versions]
versionName = "0.1.0"

kotlin = "2.1.20"
jupiter = "5.10.0"
jupiterPlatform = "1.10.0"

[libraries]

jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
jupiter-platform = { module = "org.junit.platform:junit-platform-suite", version.ref = "jupiterPlatform" }

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }